# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Qing|青
tagline:          'A blog'
description:      'Ski and coding. 滑雪|编程'
url:              https://martinqingm.github.io/
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo


plugins:
  - jekyll-paginate
paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
