# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Qing
tagline:          'A Blog'
description:      'Sking and Hard Coding. 滑雪并好好编程！'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Qing Ma'
  url:            https://github.com/MartinQingM

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/MartinQingM
